docs/behavior-stricter-utf8-library.md
[Rendered link](https://github.com/luau-lang/rfcs/blob/zeux-utf8-strict/docs/behavior-stricter-utf8-library.md)
=> Stricter utf8 library validation

docs/new-require-by-string-semantics.md, docs/require-by-string-aliases.md
The requirement to add explicitly relative paths in the form of `./path/to/file` broke backwards compatibility, so that is being updated.
=> Updates to require by string RFCs

docs/syntax-property-access-modifiers.md
Rendered: https://github.com/luau-lang/rfcs/blob/read-write-table-syntax/docs/syntax-property-access-modifiers.md
Previous PRs:
* https://github.com/luau-lang/rfcs/pull/3
* https://github.com/luau-lang/luau/pull/284
=>  RFC: Syntax for read- and write- access to properties

docs/syntax-leading-bar-and-ampersand.md
[Rendered](https://github.com/luau-lang/rfcs/blob/leading-bar-ampersand/docs/syntax-leading-bar-and-ampersand.md).
=> Allow leading `|` and `&` in types

docs/type-ascription-by-inhabitance.md
[Rendered](https://github.com/luau-lang/rfcs/blob/type-ascription-by-inhabitance/docs/type-ascription-by-inhabitance.md).
=> Improved type checking rules of cast operator

docs/syntax-attributes-functions.md
Rendered view [here](https://github.com/Dekkonot/luau-rfcs/blob/rfc-attributes/docs/syntax-attributes-functions.md).
A proposal for attributes for functions. Attributes take the form of `@identifier` and control the behavior of the language a bit more directly than we currently can. The scope of them is limited to functions right now due to feedback on prior RFCs of this nature.
The syntax as it's proposed doesn't include parameters for attributes, which might upset some people!
My justification is that I started thinking about it and I don't know what the limitations for those need to be right now. The easy answer is "literals and identifiers" but I don't have any reason to feel that way, it's just what I think is the right answer. To avoid making the *wrong* choice, I'm just not …
=> Attributes for functions

docs/syntax-key-destructuring.md
[Rendered](https://github.com/Kampfkarren/rfcs-1/blob/dict-destructuring/docs/syntax-key-destructuring.md)
=> Key destructuring (`local {.a, .b} = t`)

docs/syntax-attribute-functions-native.md
[Rendered](https://github.com/aviralg/rfcs/blob/attribute-native/docs/syntax-attribute-functions-native.md)
=> RFC: Native Attribute for Functions

docs/index-type-operator.md, docs/keyof-type-operator.md, docs/rawget-type-operator.md
We're moving towards consciously adopting the language of "type functions" consistently for this group of features as we prepare for users to get their hands on the new solver.
=> Renamed all instances of type operators to type functions

docs/syntax-attribute-functions-deprecated.md
[Rendered](https://github.com/aviralg/rfcs/blob/syntax-attribute-functions-deprecated/docs/syntax-attribute-functions-deprecated.md)
=> RFC: Deprecated Attribute for Functions

docs/function-inlining.md
This RFC addresses the idea of an `@inline` keyword in Luau. It addresses common reasons where inlining would be typically be applicable but would not apply to Luau due to metamethod dynamic dispatching, further suggesting that this feature will not be introduced to the language.
[rendered](https://github.com/dibrinsofor/rfcs/blob/func-inline/docs/function-inlining.md)
=> RFC: No Support for Function Inlining

docs/syntax-attributes-functions.md, docs/vector-library.md
[Rendered](https://github.com/ffrostflame/rfcs/blob/master/docs/vector-library.md)
=> RFC: Vector library

docs/user-defined-type-functions.md
This PR makes a small adjustment to the API surface we described in the user-defined type functions RFC (#45) to note that the read and write types are individually optional. For any pair, it's guaranteed that one of them will be present since otherwise the property would simply not be in the returned list, but the type could be read-only or write-only or have both types present.
=> Adjust signature for properties method in user-defined type functions RFC.

docs/amended-alias-resolution.md, docs/amended-require-resolution.md, docs/require-by-string-aliases.md
[Rendered](https://github.com/vrn-sn/rfcs/blob/alias-resolution-rfc/docs/amended-require-resolution.md)
We need to finalize a syntax for aliases in require expressions and determine intuitive resolution semantics as we prepare to build a package management system.
=> RFC: Amended Require Syntax and Resolution Semantics

docs/function-math-map.md
[Rendered](https://github.com/luau-lang/rfcs/blob/17bfcac8ea5f4bfff9206b0b4bb2fb1fa914a8b4/docs/function-math-map.md)
=> Add `math.map` to the standard library

docs/support-for-thread-and-buffer-types-in-user-defined-type-functions.md
[Rendered](https://github.com/luau-lang/rfcs/blob/6c73d66e7602c7620b4f9918f0e177a573779025/docs/support-for-thread-and-buffer-types-in-user-defined-type-functions.md)
=> RFC: Support for thread and buffer Types in User-Defined Type Functions

docs/function-buffer-bits.md
Rendered: [link](https://github.com/luau-lang/rfcs/blob/5194dcc12604237acf15d1647e8650d90808c3f7/docs/function-buffer-bits.md)
=> RFC: buffer.readbits/writebits

docs/function-math-lerp.md
[Rendered link](https://github.com/luau-lang/rfcs/blob/math-lerp/docs/function-math-lerp.md)
Closes #54 (by replacing it)
=> RFC: Add function math.lerp

docs/support-for-generic-function-types-in-user-defined-type-functions.md
I particular, this enables user-defined type functions to be used on Roblox DataModel types, but overall value for Luau that is full of generic functions is also great.
[Rendered](https://github.com/luau-lang/rfcs/blob/udtf-generics/docs/support-for-generic-function-types-in-user-defined-type-functions.md)
=> RFC: Support for Generic Types and Packs in User-Defined Type Functions

docs/new-require-by-string-semantics.md, docs/require-by-string-aliases.md
This PR edits the sections of the old require-by-string RFCs that were affected by the amendments RFC (https://github.com/luau-lang/rfcs/pull/56).
Also, I reorganized the aliases RFC in this PR as well to align with how the original RFC (https://github.com/luau-lang/luau/pull/969) was organized before it was split into two RFCs. It looks like some information was spliced weirdly during the split.
New versions of old RFCs:
- [Require-by-string semantics](https://github.com/vrn-sn/rfcs/blob/link-amendments-to-old-require-by-string-rfcs/docs/new-require-by-string-semantics.md)
- [Aliases](https://github.com/vrn-sn/rfcs/blob/link-amendments-to-old-require-by-string-rfcs/docs/require-by-string-aliases.md)
(This is not a new RFC.)
=> Update old require-by-string RFCs with information about amendments

docs/metatable-type-functions.md
[Rendered](https://github.com/ffrostfall/rfcs/blob/metatable-type-functions/docs/metatable-type-functions.md)
=> RFC: Metatable type functions

docs/explicit-type-parameter-instantiation.md, docs/parameterized-function-expressions.md
[Rendered](https://github.com/Kampfkarren/rfcs-1/blob/type-annotations-in-function-calls/docs/parameterized-function-expressions.md)
TL;DR -- Adds support for calling `f<<T>>()` where `f` is a function that takes a type parameter `T`, similar to Rust's turbofish (`f::<T>()`) or C++'s `f<T>()`. This is done at the expression level, so `f<<T>>` is valid as a value.
=> RFC: Explicit type parameter instantiation

docs/negation-types.md
[Rendered](https://github.com/luau-lang/rfcs/blob/negation-types/docs/negation-types.md).
=> RFC: Negation types

docs/relax-recursive-type-restriction.md
[Rendered](https://github.com/aatxe/luau-rfcs/blob/awe/relax-recursive-type-restriction/docs/relax-recursive-type-restriction.md).
=> Relax the recursive type restriction.

docs/udtf-is-extern.md
[Rendered](https://github.com/karl-police/rfcs/blob/patch-4/docs/udtf-is-extern.md)
~~``is("class")``~~
``ìs("extern")``
=> RFC: Rename tag "class" to "extern" for ExternType
